version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db
      - /data/configdb
    networks:
      - dev-net

  back:
    build:
      context: $WORKSPACE
      dockerfile: docker/config/back/Dockerfile
    container_name: back
    image: back
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=$MONGO_HOST
    networks:
      - dev-net
    depends_on:
      - mongo

networks:
  dev-net:
    external: true
